name: mapbox_gl_wasm
description: WASM-compatible web platform implementation of mapbox_gl using JavaScript interop
version: 0.16.0
homepage: https://github.com/tobrun/flutter-mapbox-gl
publish_to: none

flutter:
  plugin:
    platforms:
      web:
        pluginClass: MapboxMapWasmPlugin
        fileName: mapbox_gl_wasm.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  meta: ^1.1.7
  mapbox_gl_platform_interface:
    git:
      url: https://github.com/tobrun/flutter-mapbox-gl.git
      path: mapbox_gl_platform_interface
  mapbox_gl_dart:
    git:
      url: https://github.com/Tomison-E/mapbox-gl-dart.git
  image: '>=3.0.0 <5.0.0'

dependency_overrides:
  mapbox_gl_platform_interface:
    path: ../mapbox_gl_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

