name: mapbox_gl_dart
version: 0.3.0
description: Mapbox-gl wrapper for Dart. Library to use Mapbox GL JS in your web Dart projects. WASM compatible.
homepage: https://github.com/andrea689/mapbox-gl-dart/

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  web: ^1.0.0

dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.0
  lints: ^3.0.0
